<?php

$modversion['name'] = _UTSTATS_MOD_NAME;
$modversion['version'] = '1.0';
$modversion['description'] = _UTSTATS_MOD_DESC;
$modversion['credits'] = '<p>Original Code by Paul Gallier<br>( http://ut2003stats.sourceforge.net/ )<br>  Based on LocalStats by H3llRaiser<br>  ( http://members.tripod.com/lightspeed/ )<br>   Xoops Mod By McNaz<br>  ( http://www.fishy-wishy.net )</p>';
$modversion['help'] = 'mylinks.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/mylinks_slogo.gif';
$modversion['dirname'] = 'utstats';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'ut_players.sql';
$modversion['tables'][1] = 'ut_games.sql';
$modversion['tables'][2] = 'ut_totals.sql';
$modversion['tables'][3] = 'ut_gplayers.sql';
$modversion['tables'][4] = 'ut_gkills.sql';
$modversion['tables'][5] = 'ut_gscores.sql';
$modversion['tables'][6] = 'ut_tkills.sql';
$modversion['tables'][7] = 'ut_gevents.sql';
$modversion['tables'][8] = 'ut_pwkills.sql';
$modversion['tables'][9] = 'ut_type.sql';
$modversion['tables'][10] = 'ut_weapons.sql';
$modversion['tables'][11] = 'ut_items.sql';
$modversion['tables'][12] = 'ut_pitems.sql';
$modversion['tables'][13] = 'ut_gitems.sql';
$modversion['tables'][14] = 'ut_gchat.sql';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Blocks
$modversion['blocks'][1]['file'] = 'myalbum_photo.php';
$modversion['blocks'][1]['name'] = _UTSTATS_MOD_BLOCK1;
$modvertion['blocks'][1]['description'] = 'Shows a random photo';
$modversion['blocks'][1]['show_func'] = 'b_myalbum_photo_show';
$modversion['blocks'][1]['edit_func'] = 'b_myalbum_photo_edit';
$modversion['blocks'][1]['options'] = 'width|100';
$modversion['blocks'][2]['file'] = 'myalbum_top.php';
$modversion['blocks'][2]['name'] = _UTSTATS_MOD_BLOCK2;
$modvertion['blocks'][2]['description'] = 'Shows recently added photos';
$modversion['blocks'][2]['show_func'] = 'b_myalbum_top_show';
$modversion['blocks'][2]['edit_func'] = 'b_myalbum_top_edit';
$modversion['blocks'][2]['options'] = 'date|10';

// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _UTSTATS_MOD_SMNAME2;
$modversion['sub'][1]['url'] = 'index.php?stats=games';
$modversion['sub'][2]['name'] = _UTSTATS_MOD_SMNAME3;
$modversion['sub'][2]['url'] = 'index.php?stats=players';
$modversion['sub'][3]['name'] = _UTSTATS_MOD_SMNAME4;
$modversion['sub'][3]['url'] = 'totals.php';
$modversion['sub'][4]['name'] = _UTSTATS_MOD_SMNAME5;
$modversion['sub'][4]['url'] = 'careerhighs.php';
$modversion['sub'][5]['name'] = _UTSTATS_MOD_SMNAME6;
$modversion['sub'][5]['url'] = 'gamehighs.php';
