CREATE TABLE ut_games (
    gm_num          INT(10) UNSIGNED       NOT NULL AUTO_INCREMENT,
    gm_server       VARCHAR(35)            NOT NULL DEFAULT '',
    gm_admin        VARCHAR(35)            NOT NULL DEFAULT '',
    gm_email        VARCHAR(35)            NOT NULL DEFAULT '',
    gm_map          VARCHAR(30)            NOT NULL DEFAULT '',
    gm_type         TINYINT(3) UNSIGNED    NOT NULL DEFAULT '0',
    gm_start        DATETIME               NOT NULL DEFAULT '0000-00-00 00:00:00',
    gm_mutators     VARCHAR(120)                    DEFAULT NULL,
    gm_fraglimit    TINYINT(3) UNSIGNED    NOT NULL DEFAULT '0',
    gm_timelimit    TINYINT(3) UNSIGNED    NOT NULL DEFAULT '0',
    gm_minplayers   TINYINT(3) UNSIGNED    NOT NULL DEFAULT '0',
    gm_translocator TINYINT(3) UNSIGNED    NOT NULL DEFAULT '0',
    gm_starttime    MEDIUMINT(10) UNSIGNED NOT NULL DEFAULT '0',
    gm_length       MEDIUMINT(10) UNSIGNED NOT NULL DEFAULT '0',
    gm_numplayers   SMALLINT(5) UNSIGNED   NOT NULL DEFAULT '0',
    gm_kills        SMALLINT(5) UNSIGNED   NOT NULL DEFAULT '0',
    gm_deaths       SMALLINT(5) UNSIGNED   NOT NULL DEFAULT '0',
    gm_suicides     SMALLINT(5) UNSIGNED   NOT NULL DEFAULT '0',
    gm_t0score      SMALLINT(6)            NOT NULL DEFAULT '0',
    gm_t1score      SMALLINT(6)            NOT NULL DEFAULT '0',
    gm_firstblood   SMALLINT(6)            NOT NULL DEFAULT '-1',
    gm_headshots    SMALLINT(5) UNSIGNED   NOT NULL DEFAULT '0',
    UNIQUE KEY gm_gnum (gm_num)
);
