CREATE TABLE ut_players (
    pnum             MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
    plr_name         VARCHAR(30)           NOT NULL DEFAULT '',
    plr_bot          TINYINT(3) UNSIGNED   NOT NULL DEFAULT '0',
    plr_frags        MEDIUMINT(9)          NOT NULL DEFAULT '0',
    plr_score        MEDIUMINT(9)          NOT NULL DEFAULT '0',
    plr_kills        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_deaths       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_suicides     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_headshots    MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_firstblood   MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_transgib     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_user         VARCHAR(35)           NOT NULL DEFAULT '',
    plr_id           VARCHAR(32)           NOT NULL DEFAULT '',
    plr_key          VARCHAR(32)           NOT NULL DEFAULT '',
    dm_score         MEDIUMINT(8)          NOT NULL DEFAULT '0',
    dm_frags         MEDIUMINT(9)          NOT NULL DEFAULT '0',
    dm_kills         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dm_deaths        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dm_suicides      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dm_wins1         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dm_wins2         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dm_wins3         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dm_losses        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dm_games         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dm_time          INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    tdm_score        MEDIUMINT(8)          NOT NULL DEFAULT '0',
    tdm_frags        MEDIUMINT(8)          NOT NULL DEFAULT '0',
    tdm_kills        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    tdm_deaths       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    tdm_suicides     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    tdm_teamkills    MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    tdm_teamdeaths   MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    tdm_wins         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    tdm_losses       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    tdm_games        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    tdm_time         INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    dd_score         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dd_frags         MEDIUMINT(8)          NOT NULL DEFAULT '0',
    dd_kills         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dd_deaths        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dd_suicides      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dd_teamkills     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dd_teamdeaths    MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dd_wins          MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dd_losses        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dd_games         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    dd_time          INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    dd_cpcapture     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_score        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_frags        MEDIUMINT(8)          NOT NULL DEFAULT '0',
    ctf_kills        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_deaths       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_suicides     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_teamkills    MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_teamdeaths   MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_wins         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_losses       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_games        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_time         INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    ctf_flagcapture  MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_flagdrop     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_flagpickup   MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_flagreturn   MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_flagtaken    MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_flagkill     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    ctf_flagassist   MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_score         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_frags         MEDIUMINT(8)          NOT NULL DEFAULT '0',
    br_kills         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_deaths        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_suicides      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_teamkills     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_teamdeaths    MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_wins          MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_losses        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_games         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_time          INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    br_bombcarried   MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_bombtossed    MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_bombdrop      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_bombpickup    MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_bombtaken     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_bombkill      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    br_bombassist    MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    mu_score         MEDIUMINT(8)          NOT NULL DEFAULT '0',
    mu_frags         MEDIUMINT(9)          NOT NULL DEFAULT '0',
    mu_kills         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    mu_deaths        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    mu_suicides      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    mu_wins1         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    mu_wins2         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    mu_wins3         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    mu_losses        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    mu_games         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    mu_time          INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    in_score         MEDIUMINT(8)          NOT NULL DEFAULT '0',
    in_frags         MEDIUMINT(9)          NOT NULL DEFAULT '0',
    in_kills         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    in_deaths        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    in_suicides      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    in_teamkills     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    in_teamdeaths    MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    in_wins1         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    in_wins2         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    in_wins3         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    in_losses        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    in_games         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    in_time          INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    lm_score         MEDIUMINT(8)          NOT NULL DEFAULT '0',
    lm_frags         MEDIUMINT(9)          NOT NULL DEFAULT '0',
    lm_kills         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    lm_deaths        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    lm_suicides      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    lm_wins          MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    lm_losses        MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    lm_games         MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    lm_time          INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    other_score      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    other_frags      MEDIUMINT(8)          NOT NULL DEFAULT '0',
    other_kills      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    other_deaths     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    other_suicides   MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    other_teamkills  MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    other_teamdeaths MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    other_wins       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    other_losses     MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    other_games      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    other_time       INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    plr_multi1       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_multi2       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_multi3       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_multi4       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_multi5       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_multi6       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_multi7       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spree1       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spreet1      INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    plr_spreek1      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spree2       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spreet2      INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    plr_spreek2      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spree3       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spreet3      INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    plr_spreek3      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spree4       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spreet4      INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    plr_spreek4      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spree5       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spreet5      INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    plr_spreek5      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spree6       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_spreet6      INT(10) UNSIGNED      NOT NULL DEFAULT '0',
    plr_spreek6      MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_combo1       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_combo2       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_combo3       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    plr_combo4       MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
    UNIQUE KEY pnum (pnum),
    KEY plr_usrid (plr_user, plr_id)
);
